[tox]
env_list =
    py36
    py37
    py38
    py39
    py310
    py311
    py312
    pypy3
skip_missing_interpreters = true

[testenv]
description = Run unit and functional tests
package = editable
deps =
    -rrequirements-testing.txt
commands =
    pytest --verbose --verbose --cov=xmodem {posargs}

[testenv:docs]
description = Build Sphinx documentation
basepython = python3.11
deps =
    -rrequirements-docs.txt
commands =
    sphinx-build -b html doc/source doc/build/html

[testenv:coveralls]
description = Upload coverage to Coveralls
basepython = python3.11
deps =
    PyYAML
    coveralls
commands =
    coveralls

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
